
name: CI

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy_to_prod_server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 22
          script: |
            ls -la
            cd /var/www/rbk/
            git pull origin master
            docker exec rbk-php bash -c "composer install --optimize-autoloader"
            docker exec rbk-php bash -c "php artisan migrate --force"
            docker exec rbk-php bash -c "php artisan db:seed --force"
            docker exec rbk-php bash -c "php artisan cache:clear"
            docker exec rbk-php bash -c "php artisan view:clear"
            docker exec rbk-php bash -c "php artisan config:clear"
